# fiber configuration
# Defaults are shown, commented out
# Some values have no defaults and must be filled in
[node]
genesis_signature_str = "3cca6efdf1dfc5d171cbb76a60dd86df91b421139593884d32b2a6bf51ae4130263bbe654eced0f6a83799f71d85946a9340d0fa14e711410447f485f35fdeed00"
genesis_address_str = "vczdwAwVsyVoGyZCFBoRPyWU3Qq35Ln1XB"
blockchain_pubkey_str = "02f37a1c7ebb2716404c1973cd5b3132a313e77b848fa25628bf1520d05365c5dc"
blockchain_seckey_str = ""
genesis_timestamp = 1554976303
genesis_coin_volume = 100e4
default_connections = [
	"64.227.22.96:9982",
	"104.248.121.138:9982",
	"64.227.28.104:9982",
]
peer_list_url = "https://raw.githubusercontent.com/M3ND3X/amolenodes/master/nodes.txt"
port = 9982
web_interface_port = 9981
# unconfirmed_burn_factor = 2
# unconfirmed_max_transaction_size = 32 * 1024
# unconfirmed_max_decimals = 3
# create_block_burn_factor = 2
# create_block_max_transaction_size = 32 * 1024
# create_block_max_decimals = 3
# max_block_size = 32 * 1024

[params]
max_coin_supply = 1e8
distribution_addresses_total = 5
initial_unlocked_count = 5
unlock_addresss_rate = 5
unlocked_time_internal = 60 * 60 * 24 * 365
user_max_decimals = 3
# user_max_transaction_size = 32 * 1024
# user_burn_factor = 2
distribution_addresses = [
        "25qV7Dk1ywCUWFk5KwhhZFve3WgUSdTG7mk",
	"sznjYQDwxJejVg5pX37Nr66TTaG47JbLMR",
	"qafY6RDmEuDXa3PmgnQTEvfM4ckCRtD8PX",
	"228VCv1BGyYRrYzjwVh5X4F1oSjqyqbmxRr",
	"5a1hUVMgBB6cQn9TkUf4dxdL7iwcxUzYZT",
]
